### PR TITLE
add support for MTU in network-status

### PR DESCRIPTION
**Pull request by SchSeba**

### CODE REVIEW

**Comment by SchSeba** [comment]
@s1061123 @dougbtv please take a look when you have time :)

**Comment by dougbtv** [comment]
Hey Sebastian -- would you mind making a change proposal, this is an example from Miguel's recent change: [IPAM lease proposal](https://docs.google.com/document/d/1HjPZCfl_3zsXr905T620mF7OFt2QnwxLZomPbeDj0vc)

And then bring it to the NPWG call? We typically have a discussion and then a vote (plus it's hard to see the diff on the .bin files)

**Comment by SchSeba** [comment]
Hi @dougbtv sure no problem the change is pretty simple :P

https://docs.google.com/document/d/1IX_4xrlotEhH54fe6o1t_RAOL6XTE-x9RpCihCE3bQs/edit?usp=sharing

**Comment by SchSeba** [comment]
Hi @dougbtv let me know if we can merge this one after the approval on the npwg meeting last week :)

**Review by dougbtv — APPROVED** [review]
LGTM! Thank you

**Pull request merged**
